kernel.o: src/kernel.c src/gdt.h src/pic.h src/ports.h src/stdutils.h \
 src/ps2/control_rs.h
stdutils.o: src/stdutils.c
gdt.o: src/gdt.c src/gdt.h
pic.o: src/pic.c src/pic.h src/ports.h
ports.o: src/ports.c src/ports.h
