[package]
name = "test_mod"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
debug = true

[dependencies]
paging = { version = "0.1.0", path = "../paging" }
dyshared = { version = "0.1.0", path = "../dyshared" }
process = { version = "0.1.0", path = "../process" }
test_dep = { version = "0.1.0", path = "../test_dep" }
interrupts = { version = "0.1.0", path = "../interrupts" }
pic = { version = "0.1.0", path = "../pic" }
